-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 23:35:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Facegram
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Facegram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Facegram` DEFAULT CHARACTER SET utf8 ;
USE `Facegram` ;

-- -----------------------------------------------------
-- Table `Facegram`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Facegram`.`users` ;

CREATE TABLE IF NOT EXISTS `Facegram`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Facegram`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Facegram`.`comments` ;

CREATE TABLE IF NOT EXISTS `Facegram`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Facegram`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Facegram`.`posts` ;

CREATE TABLE IF NOT EXISTS `Facegram`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `img_url` TEXT NOT NULL,
  `post_text` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  `user_id` INT NOT NULL,
  `comment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_posts_comments1_idx` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Facegram`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_comments1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `Facegram`.`comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Facegram`.`posts_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Facegram`.`posts_has_users` ;

CREATE TABLE IF NOT EXISTS `Facegram`.`posts_has_users` (
  `posts_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`posts_id`, `user_id`),
  INDEX `fk_posts_has_users_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_posts_has_users_posts1_idx` (`posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_has_users_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `Facegram`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Facegram`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
